In [2]:
# Import modules
from __future__ import print_function
import tensorflow as tf
import numpy as np
import time
import os
import matplotlib.pyplot as plt
try:
    import _pickle as pickle
except ImportError:
    import pickle as pickle

from ecbm4040.cifar_utils import load_data

# Plot configurations
% matplotlib inline

# Notebook auto reloads code. (Ref: http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython)
% load_ext autoreload
% autoreload 2

In [2]:
# Load the raw CIFAR-10 data.
X_train, y_train, X_test, y_test = load_data()

# Data organizations:
# Train data: 49000 samples from original train set: 1~49,000
# Validation data: 1000 samples from original train set: 49,000~50,000
# Test data: 10000 samples from original test set: 1~10,000
# Development data (for gradient check): 100 from the train set: 1~49,000
num_training = 49000
num_validation = 1000
num_dev = 100

X_val = X_train[-num_validation:, :]
y_val = y_train[-num_validation:]

mask = np.random.choice(num_training, num_dev, replace=False)
X_dev = X_train[mask]
y_dev = y_train[mask]

X_train = X_train[:num_training, :]
y_train = y_train[:num_training]

# Preprocessing: subtract the mean value across every dimension for training data
mean_image = np.mean(X_train, axis=0)

X_train = X_train.astype(np.float32) - mean_image.astype(np.float32)
X_val = X_val.astype(np.float32) - mean_image
X_test = X_test.astype(np.float32) - mean_image
X_dev = X_dev.astype(np.float32) - mean_image

print(X_train.shape, X_val.shape, X_test.shape, X_dev.shape)
print('Train data shape: ', X_train.shape)
print('Train labels shape: ', y_train.shape)
print('Validation data shape: ', X_val.shape)
print('Validation labels shape: ', y_val.shape)
print('Test data shape: ', X_test.shape)
print('Test labels shape: ', y_test.shape)
print('Development data shape:', X_dev.shape)
print('Development data shape', y_dev.shape)

(49000, 3072) (1000, 3072) (10000, 3072) (100, 3072)
Train data shape:  (49000, 3072)
Train labels shape:  (49000,)
Validation data shape:  (1000, 3072)
Validation labels shape:  (1000,)
Test data shape:  (10000, 3072)
Test labels shape:  (10000,)
Development data shape: (100, 3072)
Development data shape (100,)


In [3]:
x = X_dev
w = np.random.rand(x.shape[1],100)
b = np.random.rand(100)
dout = np.ones((x.shape[0],100))

In [6]:
def affine_forward(X, W,b):
    out = X.dot(W) + b
    return out

In [7]:
def affine_backward(dout, X, w,b):
    dx = dout.dot(w.transpose())
    dw = x.transpose().dot(dout)
    db = np.identity(dout.shape[0]).dot(dout)
    
    return dx, dw, db

In [1]:
par = [100, 0.25, 20, 500, 47.78]

In [2]:
par2 = [100, 0.25,14,500, 47.3]

In [3]:
par3 = [100, 0.25, 20, 500, 1e-2, 47.9]

In [4]:
par4 = [100, 0.25, 20, 500, 1e-1, 48.7]

In [5]:
par5 = [100, 0.3, 15, 500, 1e-1, 49.66]

In [6]:
par6 = [100, 0.3, 20, 500, 1e-1, 48.2]

In [2]:
import numpy as np
A = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20]]])

In [5]:
A = np.random.randn(5,4,3,2)

In [6]:
A.shape

(5, 4, 3, 2)

In [8]:
B = np.reshape(A, (A.shape[0],-1))

In [9]:
B.shape

(5, 24)

In [10]:
Temp = []
num_channel = A.shape[-1]
for i in range(num_channel):
    Temp.append(A[:,:,:,i])


In [13]:
np.array(Temp).T.shape

(3, 4, 5, 2)

In [19]:
C = np.random.randn(3,2)
D = np.random.randn(3,2)
E = np.append(C,D, axis=1)

In [20]:
E.shape

(3, 4)

In [1]:
import numpy as np
A = np.random.randn(5,4)

In [6]:
C = np.random.choice(range(A.shape[0]), size=2)

In [5]:
np.random.choice()

array([4, 2])

In [7]:
C

array([2, 1])

In [8]:
np.random.randint(A.shape[0], size= 2)

array([3, 0])

In [10]:
np.log(1e-100)

-230.25850929940458